/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "bitrev.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_zero_input_gives_zero_output(void);
extern void test_0xFF_input_gives_0xFF_output(void);
extern void test_0x01_input_gives_0x80_output(void);
extern void test_0xFE_input_gives_0x7F_output(void);
extern void test_0x7F_input_gives_0xFE_output(void);
extern void test_0x55_input_gives_0xAA_output(void);
extern void test_passing_the_output_back_in_gives_the_original_value(void);


/*=======Suite Setup=====*/
static void suite_setup(void)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures)
{
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  suite_setup();
  UnityBegin("test/testBitrev.c");
  RUN_TEST(test_zero_input_gives_zero_output, 14);
  RUN_TEST(test_0xFF_input_gives_0xFF_output, 25);
  RUN_TEST(test_0x01_input_gives_0x80_output, 36);
  RUN_TEST(test_0xFE_input_gives_0x7F_output, 47);
  RUN_TEST(test_0x7F_input_gives_0xFE_output, 58);
  RUN_TEST(test_0x55_input_gives_0xAA_output, 69);
  RUN_TEST(test_passing_the_output_back_in_gives_the_original_value, 79);

  return suite_teardown(UnityEnd());
}
